#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
touch /tmp/last_ebus_readall.txt


docker exec ebusd ebusctl read -m 0 -c energymgr aux_1_afr && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr aux_1_mean && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr aux_2_afr_mean && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr aux_2_pump && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr config_version_counter && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heat_ext_temp_offset && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr cooling_active && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr boiler_3way_valve && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr dhw_pv_delta_t_setp && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr dhw_store_temp && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr electric_cost && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr energymgr_aux1_input && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr energymgr_aux1_out && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr energymgr_aux2_out && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr energymgr_hv_inv_1_status && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr energymgr_hv_inv_2_status && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr energymgr_hv_inv_3_status && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr ext_boiler_dhw_efficiency && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr ext_boiler_heat_efficiency && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr ext_temp_offset && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr gas_cost && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr gas_electric_energy_ratio && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr gas_electric_max_cost_ratio && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr gas_electric_min_cost_ratio && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr heat_mode && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr heating_mode && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr hv_inv_1_mean && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr hv_inv_2_mean && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr hv_inv_3_mean && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr hybrid_logic && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr hybrid_mode && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr hybrid_status && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr hydraulic_scheme && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr protech_anode && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr pump_antiblock && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr pv_electric_cost && sleep 2
docker exec ebusd ebusctl read -m 0 -c gateway gateway_activation_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c gateway gateway_ntp && sleep 2
docker exec ebusd ebusctl read -m 0 -c gateway gateway_sw_update && sleep 2
docker exec ebusd ebusctl read -m 0 -c gateway gateway_wifi && sleep 2
docker exec ebusd ebusctl read -m 0 -c gateway gateway_wifi_signal && sleep 2
docker exec ebusd ebusctl read -m 0 -c gateway gateway_wifi_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump config_version_counter && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_3way_valve_dhw_heat && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_3way_valve_heat_cool && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_4way_valve_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_anode && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_base_pane_heater_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_compr_current && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_compr_modulation && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_compressor_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_cond_pressure && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_evap_pressure && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_exp_valve && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_ext_pump && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_fan1_speed && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_fan1_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_fan2_speed && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_fan2_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_flow_switch && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_inverter_nominal_power && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_main_pump && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_preheater_state && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_safety_thermostat && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump heatpump_shutoff_protection && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump pump_max_pwm && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump pump_min_pwm && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump pump_operation && sleep 2
docker exec ebusd ebusctl read -m 0 -c heatpump silent_mode && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr heatpump_calculated_cost && sleep 2
docker exec ebusd ebusctl read -m 0 -c energymgr boiler_calculated_cost && sleep 2